### ISSUE TITLE
是不是缺少文件呀

### ISSUE THREAD

**Issue by iaoxuesheng** [PharMolix/OpenBioMed#24]
一直报这个错误

(biomed) E:\OpenBioMed\open_biomed>python run.py
Config:  {'name': 'biomedgptv', 'data': {'mol': {'modality': ['structure'], 'featurizer': {'structure': {'name': 'BaseGNN'}}}, 'protein': {'modality': ['structure'], 'featurizer': {'structure': {'name': 'transformertok', 'transformer_type': 'esm', 'model_name_or_path': 'E:\\OpenBioMed/ckpts/protein_ckpts/esm2-3b', 'max_length': 1024}}}}, 'network': {'mol': {'gin_hidden_dim': 300, 'gin_num_layers': 5, 'drop_ratio': 0.0, 'max_n_nodes': 256, 'freeze': True}, 'protein': {'model_name_or_path': 'E:\\OpenBioMed/ckpts/protein_ckpts/esm2-3b', 'lora': False, 'freeze': True, 'use_float16': True}, 'llm': {'model_name_or_path': 'E:\\OpenBioMed/ckpts/text_ckpts/biomed-llama-7b', 'use_float16': True}}}
Traceback (most recent call last):
  File "E:\OpenBioMed\open_biomed\run.py", line 19, in <module>
    model = BioMedGPTV(config["network"])
  File "E:\OpenBioMed\open_biomed\models\multimodal\biomedgpt\biomedgpt.py", line 101, in __init__
    self.prot_structure_config = EsmConfig.from_json_file(os.path.join(config["protein"]["model_name_or_path"], "config.json"))
  File "D:\conda\envs\biomed\lib\site-packages\transformers\configuration_utils.py", line 744, in from_json_file
    config_dict = cls._dict_from_json_file(json_file)
  File "D:\conda\envs\biomed\lib\site-packages\transformers\configuration_utils.py", line 749, in _dict_from_json_file
    with open(json_file, "r", encoding="utf-8") as reader:
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\OpenBioMed/ckpts/protein_ckpts/esm2-3b\\config.json'
缺少了这里面的两个模型文件呀，这个esm2-3b和biomed-llama-7b文件是什么呀，在哪有这两个文件呀？

**Comment by icycookies** [comment]
模型的checkpoint文件是用同一个文件存储的，但文本模型和蛋白质模型的网络结构设置（与Llama-2-7B和ESM2-3B结构一致）分别存储在`OpenBioMed-main/ckpts/text_ckpts/biomed-llama-7b/config.json`和`OpenBioMed-main/ckpts/protein_ckpts/esm2-3b/config.json`中，请从[此处](https://huggingface.co/PharMolix/BioMedGPT-LM-7B/tree/main)和[此处](https://huggingface.co/facebook/esm2_t36_3B_UR50D/tree/main)下载两个config文件（无需下载模型参数），放置在对应位置即可加载BioMedGPT-10B。

感谢您对BioMedGPT的关注和支持！

**Comment by iaoxuesheng** [comment]
您好，感谢您帮我解决问题，那个模型文件里面是不是缺少了一个关键字呀，我在跑模型的时候出了这个错误
Traceback (most recent call last):
  File "E:\OpenBioMed\open_biomed\run.py", line 21, in <module>
    model.load_state_dict(ckpt)
  File "D:\conda\envs\biomed\lib\site-packages\torch\nn\modules\module.py", line 1667, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for BioMedGPTV:
        Missing key(s) in state_dict: "prot_structure_encoder.embeddings.position_ids".

**Comment by icycookies** [comment]
BioMedGPT-10B没有使用蛋白质序列的position embedding，可能是由于transformers包的版本差异导致ESM2模型的结构不同。一个简单的解决方案是改为：model.load_state_dict(ckpt, strict=False)

**Comment by iaoxuesheng** [comment]
感谢博主，还有最后一个问题，您的文档里面说10B模型需要的显存是20G，但是我单张4090爆显存了呀，24G的还不够跑呀，请问这个有量化版本嘛？或者有其他解决办法嘛

**Comment by iaoxuesheng** [comment]
感谢博主，还有最后一个问题，您的文档里面说10B模型需要的显存是20G，但是我单张4090爆显存了呀，24G的还不够跑呀，而且我改成1.6B的模型仍然爆显存，请问这是怎么回事呀，请问这个有量化版本嘛？或者有其他解决办法嘛




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PharMolix/OpenBioMed"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月21日(星期一) 下午4:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PharMolix/OpenBioMed] 是不是缺少文件呀 (Issue #24)





 
BioMedGPT-10B没有使用蛋白质序列的position embedding，可能是由于transformers包的版本差异导致ESM2模型的结构不同。一个简单的解决方案是改为：model.load_state_dict(ckpt, strict=False)

**Comment by icycookies** [comment]
非常抱歉！BioMedGPT-10B实测消耗了39GB的显存。可以尝试将open_biomed/models/multimodal/biomedgpt/biomedgpt.py中103和126行的torch_dtype改为float8

**Comment by icycookies** [comment]
原先实现中fp16量化存在问题，在最新的commit中已经修复，目前使用20GB显存即可支持BioMedGPT-10B预测。

**Comment by iaoxuesheng** [comment]
您好，关于esm-3b蛋白质模型里缺少tokenizer文件您是怎么解决的，我的报错信息如下
Traceback (most recent call last):
&nbsp; File "E:\OpenBioMed\open_biomed\run.py", line 30, in <module&gt;
&nbsp; &nbsp; chat = Conversation(
&nbsp; File "E:\OpenBioMed\open_biomed\utils\chat_utils.py", line 20, in __init__
&nbsp; &nbsp; self.prot_processor = DataProcessorFast("protein", processor_config["protein"])
&nbsp; File "E:\OpenBioMed\open_biomed\utils\data_utils.py", line 37, in __init__
&nbsp; &nbsp; self.featurizer = feat[0][feat_config["name"]](feat_config)
&nbsp; File "E:\OpenBioMed\open_biomed\feature\protein_featurizer.py", line 102, in __init__
&nbsp; &nbsp; self.tokenizer = AutoTokenizer.from_pretrained(config["model_name_or_path"], model_max_length=self.max_length)
&nbsp; File "D:\conda\envs\biomed\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 714, in from_pretrained
&nbsp; &nbsp; return tokenizer_class_py.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
&nbsp; File "D:\conda\envs\biomed\lib\site-packages\transformers\tokenization_utils_base.py", line 1796, in from_pretrained
&nbsp; &nbsp; raise EnvironmentError(
OSError: Can't load tokenizer for 'E:\OpenBioMed/ckpts/protein_ckpts/esm2-3b'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'E:\OpenBioMed/ckpts/protein_ckpts/esm2-3b' is the correct path to a directory containing all relevant files for a EsmTokenizer tokenizer.





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PharMolix/OpenBioMed"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月22日(星期二) 下午2:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PharMolix/OpenBioMed] 是不是缺少文件呀 (Issue #24)





 
原先实现中fp16量化存在问题，在最新的commit中已经修复，目前使用20GB显存即可支持BioMedGPT-10B预测。

**Comment by xt-mao** [comment]
> 您好，关于esm-3b蛋白质模型里缺少tokenizer文件您是怎么解决的，我的报错信息如下 Traceback (most recent call last): &nbsp; File "E:\OpenBioMed\open_biomed\run.py", line 30, in <module&gt; &nbsp; &nbsp; chat = Conversation( &nbsp; File "E:\OpenBioMed\open_biomed\utils\chat_utils.py", line 20, in __init__ &nbsp; &nbsp; self.prot_processor = DataProcessorFast("protein", processor_config["protein"]) &nbsp; File "E:\OpenBioMed\open_biomed\utils\data_utils.py", line 37, in __init__ &nbsp; &nbsp; self.featurizer = feat[0][feat_config["name"]](feat_config) &nbsp; File "E:\OpenBioMed\open_biomed\feature\protein_featurizer.py", line 102, in __init__ &nbsp; &nbsp; self.tokenizer = AutoTokenizer.from_pretrained(config["model_name_or_path"], model_max_length=self.max_length) &nbsp; File "D:\conda\envs\biomed\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 714, in from_pretrained &nbsp; &nbsp; return tokenizer_class_py.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs) &nbsp; File "D:\conda\envs\biomed\lib\site-packages\transformers\tokenization_utils_base.py", line 1796, in from_pretrained &nbsp; &nbsp; raise EnvironmentError( OSError: Can't load tokenizer for 'E:\OpenBioMed/ckpts/protein_ckpts/esm2-3b'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'E:\OpenBioMed/ckpts/protein_ckpts/esm2-3b' is the correct path to a directory containing all relevant files for a EsmTokenizer tokenizer.
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "PharMolix/OpenBioMed" ***@***.***&gt;; 发送时间:&nbsp;2023年8月22日(星期二) 下午2:08 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [PharMolix/OpenBioMed] 是不是缺少文件呀 (Issue #24) 原先实现中fp16量化存在问题，在最新的commit中已经修复，目前使用20GB显存即可支持BioMedGPT-10B预测。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

You can download config.json, tokenizer_config.json, vocab.txt for ESM2-3B (https://huggingface.co/facebook/esm2_t36_3B_UR50D/tree/main) and put them under OpenBioMed/ckpts/protein_ckpts/esm2-3b

**Comment by icycookies** [comment]
请参考最新的jupytor notebook，需要从hugging face中下载ESM2-3B的模型结构设置文件和tokenizer设置文件。

**Comment by iaoxuesheng** [comment]
非常感谢博主的解答，我一直在关注您的项目，本人接触的比较少，想学习学习您的项目，感谢您耐心的解答，项目可以运行了，后面还会继续关注，最好可以出一个连续提问的，能有web界面就更好了哈哈哈

**Comment by icycookies** [comment]
感谢您的支持与关注！我们会在未来的更新中支持多轮对话和web前端，敬请期待！
