### ISSUE TITLE
BioMedGPT-10B 模型加载过程中异常

### ISSUE THREAD

**Issue by AkiraLan** [PharMolix/OpenBioMed#30]
在使用模板 biomedgpt_inference.ipynb 过程中，运行到 
```
ckpt = torch.load("../ckpts/fusion_ckpts/biomedgpt_10b.pth")
model.load_state_dict(ckpt)
```
这里，报错：

```
Traceback (most recent call last):
  File "/root/.cache/JetBrains/RemoteDev/dist/1ed71c3cc0a96_pycharm-professional-2023.2/plugins/python/helpers/pydev/pydevd.py", line 1500, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/root/.cache/JetBrains/RemoteDev/dist/1ed71c3cc0a96_pycharm-professional-2023.2/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/root/autodl-tmp/OpenBioMed-main/examples/biomedgpt.py", line 23, in <module>
    model.load_state_dict(ckpt)
  File "/root/miniconda3/envs/OpenBioMed/lib/python3.9/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for BioMedGPTV:
	Missing key(s) in state_dict: "prot_structure_encoder.embeddings.position_ids".a
```

想请问下，可能是由什么原因导致的呢？

此外，似乎 transformers的新版本 4.32.0 有些兼容性异常，在跑到
`model = BioMedGPTV(config["network"])`
时会报错
`UnboundLocalError: local variable 'sentencepiece_model_pb2' referenced before assignment`
降级到依赖里声明的最低版本4.28.1 后正常了

**Comment by xt-mao** [comment]
Try transformers package. 4.31.0 

[https://github.com/PharMolix/OpenBioMed/issues/29](url)
